# Generated by Django 4.2.8 on 2023-12-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0001_initial'),
    ]

    operations = [
    ]
