# Generated by Django 4.2.8 on 2023-12-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('PROCESSING', 'Processing'), ('RECEIVED', 'Received'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], max_length=15),
        ),
    ]
