# Generated by Django 4.2.8 on 2023-12-15 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0002_auto_20231215_0357'),
    ]

    operations = [
    ]
