# Generated by Django 4.2.8 on 2023-12-12 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactionapp', '0002_alter_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receivedAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sentAmount',
            field=models.FloatField(),
        ),
    ]
