# Generated by Django 4.2.8 on 2023-12-12 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactionapp', '0003_remove_sender_user_transaction_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumerName', models.CharField(max_length=100)),
                ('consumerId', models.CharField(blank=True, max_length=100, null=True)),
                ('companyName', models.CharField(max_length=100)),
                ('Amount', models.FloatField()),
                ('status', models.CharField(blank=True, choices=[('PROCESSING', 'Processing'), ('RECEIVED', 'Received'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('completed_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
