# Generated by Django 4.2.8 on 2023-12-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0004_alter_paytransaction_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertransaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
