# Generated by Django 4.2.8 on 2023-12-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0004_buytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytransaction',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
