# Generated by Django 4.2.8 on 2023-12-14 16:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactionapp', '0005_buytransaction_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='TransferTransaction',
        ),
    ]
