# Generated by Django 4.2.8 on 2023-12-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0006_rename_transaction_transfertransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='buytransaction',
            name='completed_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='buytransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sender',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='completed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
