# Generated by Django 4.2.8 on 2023-12-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0006_alter_transfertransaction_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytransaction',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='paytransaction',
            name='created_at',
        ),
    ]
