# Generated by Django 4.2.8 on 2023-12-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_account_address_account_city_account_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
