# Generated by Django 4.2.8 on 2023-12-18 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestedAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACCEPT', 'Accept'), ('DECLINE', 'Decline')], default='DECLINE', max_length=10)),
                ('requestedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_transactions_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_transactions_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
